-- Krowba MVP Database Schema
-- A trust layer for African social commerce

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- SELLERS TABLE
-- Stores seller profile information
-- ============================================
CREATE TABLE IF NOT EXISTS sellers (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  business_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  verification_score INTEGER DEFAULT 0,
  total_transactions INTEGER DEFAULT 0,
  successful_transactions INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE sellers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "sellers_select_own" ON sellers FOR SELECT USING (auth.uid() = id);
CREATE POLICY "sellers_insert_own" ON sellers FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "sellers_update_own" ON sellers FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "sellers_delete_own" ON sellers FOR DELETE USING (auth.uid() = id);

-- ============================================
-- ITEMS TABLE
-- Product listings created by sellers
-- ============================================
CREATE TABLE IF NOT EXISTS items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  seller_id UUID NOT NULL REFERENCES sellers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(12, 2) NOT NULL,
  delivery_fee DECIMAL(12, 2) DEFAULT 0,
  currency TEXT DEFAULT 'KES',
  images TEXT[] DEFAULT '{}',
  image_hashes TEXT[] DEFAULT '{}',
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'flagged')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "items_select_all" ON items FOR SELECT USING (true);
CREATE POLICY "items_insert_own" ON items FOR INSERT WITH CHECK (auth.uid() = seller_id);
CREATE POLICY "items_update_own" ON items FOR UPDATE USING (auth.uid() = seller_id);
CREATE POLICY "items_delete_own" ON items FOR DELETE USING (auth.uid() = seller_id);

-- ============================================
-- KROWBA LINKS TABLE
-- Payment links generated by sellers
-- ============================================
CREATE TABLE IF NOT EXISTS krowba_links (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  seller_id UUID NOT NULL REFERENCES sellers(id) ON DELETE CASCADE,
  item_id UUID REFERENCES items(id) ON DELETE SET NULL,
  short_code TEXT UNIQUE NOT NULL,
  item_name TEXT NOT NULL,
  item_price DECIMAL(12, 2) NOT NULL,
  delivery_fee DECIMAL(12, 2) DEFAULT 0,
  currency TEXT DEFAULT 'KES',
  escrow_mode TEXT NOT NULL CHECK (escrow_mode IN ('split_risk', 'full_escrow')),
  deposit_amount DECIMAL(12, 2),
  images TEXT[] DEFAULT '{}',
  ai_verification_status TEXT DEFAULT 'pending' CHECK (ai_verification_status IN ('pending', 'passed', 'warning', 'failed')),
  ai_verification_message TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paid', 'completed', 'cancelled', 'disputed')),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE krowba_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "krowba_links_select_all" ON krowba_links FOR SELECT USING (true);
CREATE POLICY "krowba_links_insert_own" ON krowba_links FOR INSERT WITH CHECK (auth.uid() = seller_id);
CREATE POLICY "krowba_links_update_own" ON krowba_links FOR UPDATE USING (auth.uid() = seller_id);
CREATE POLICY "krowba_links_delete_own" ON krowba_links FOR DELETE USING (auth.uid() = seller_id);

-- ============================================
-- TRANSACTIONS TABLE
-- Payment records for buyer purchases
-- ============================================
CREATE TABLE IF NOT EXISTS transactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  krowba_link_id UUID NOT NULL REFERENCES krowba_links(id) ON DELETE CASCADE,
  seller_id UUID NOT NULL REFERENCES sellers(id),
  buyer_phone TEXT NOT NULL,
  buyer_name TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  payment_type TEXT NOT NULL CHECK (payment_type IN ('deposit', 'full', 'balance')),
  payment_method TEXT DEFAULT 'mpesa',
  payment_reference TEXT,
  payhero_reference TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "transactions_select_seller" ON transactions FOR SELECT USING (auth.uid() = seller_id);
CREATE POLICY "transactions_insert_any" ON transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "transactions_update_service" ON transactions FOR UPDATE USING (true);

-- ============================================
-- ESCROW HOLDS TABLE
-- Funds held in escrow until delivery
-- ============================================
CREATE TABLE IF NOT EXISTS escrow_holds (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  transaction_id UUID NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  krowba_link_id UUID NOT NULL REFERENCES krowba_links(id),
  seller_id UUID NOT NULL REFERENCES sellers(id),
  amount DECIMAL(12, 2) NOT NULL,
  currency TEXT DEFAULT 'KES',
  status TEXT DEFAULT 'held' CHECK (status IN ('held', 'released', 'refunded', 'disputed')),
  released_at TIMESTAMPTZ,
  refunded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE escrow_holds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "escrow_holds_select_seller" ON escrow_holds FOR SELECT USING (auth.uid() = seller_id);
CREATE POLICY "escrow_holds_insert_any" ON escrow_holds FOR INSERT WITH CHECK (true);
CREATE POLICY "escrow_holds_update_service" ON escrow_holds FOR UPDATE USING (true);

-- ============================================
-- SHIPPING PROOFS TABLE
-- Dispatch evidence uploaded by sellers
-- ============================================
CREATE TABLE IF NOT EXISTS shipping_proofs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  transaction_id UUID NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  krowba_link_id UUID NOT NULL REFERENCES krowba_links(id),
  seller_id UUID NOT NULL REFERENCES sellers(id),
  courier_name TEXT NOT NULL,
  courier_contact TEXT,
  tracking_number TEXT,
  dispatch_images TEXT[] DEFAULT '{}',
  dispatch_video TEXT,
  ai_comparison_score DECIMAL(5, 2),
  ai_comparison_status TEXT DEFAULT 'pending' CHECK (ai_comparison_status IN ('pending', 'matched', 'warning', 'mismatch')),
  dispatched_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE shipping_proofs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "shipping_proofs_select_all" ON shipping_proofs FOR SELECT USING (true);
CREATE POLICY "shipping_proofs_insert_seller" ON shipping_proofs FOR INSERT WITH CHECK (auth.uid() = seller_id);
CREATE POLICY "shipping_proofs_update_seller" ON shipping_proofs FOR UPDATE USING (auth.uid() = seller_id);

-- ============================================
-- DELIVERY CONFIRMATIONS TABLE
-- Buyer confirmation of receipt
-- ============================================
CREATE TABLE IF NOT EXISTS delivery_confirmations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  transaction_id UUID NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  krowba_link_id UUID NOT NULL REFERENCES krowba_links(id),
  buyer_phone TEXT NOT NULL,
  confirmed BOOLEAN DEFAULT false,
  confirmation_code TEXT,
  confirmed_at TIMESTAMPTZ,
  auto_confirmed BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE delivery_confirmations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "delivery_confirmations_select_all" ON delivery_confirmations FOR SELECT USING (true);
CREATE POLICY "delivery_confirmations_insert_any" ON delivery_confirmations FOR INSERT WITH CHECK (true);
CREATE POLICY "delivery_confirmations_update_any" ON delivery_confirmations FOR UPDATE USING (true);

-- ============================================
-- DISPUTES TABLE
-- Conflict records between buyers and sellers
-- ============================================
CREATE TABLE IF NOT EXISTS disputes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  transaction_id UUID NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  krowba_link_id UUID NOT NULL REFERENCES krowba_links(id),
  seller_id UUID NOT NULL REFERENCES sellers(id),
  initiated_by TEXT NOT NULL CHECK (initiated_by IN ('buyer', 'seller', 'system')),
  reason TEXT NOT NULL,
  description TEXT,
  evidence_images TEXT[] DEFAULT '{}',
  evidence_video TEXT,
  ai_analysis TEXT,
  resolution TEXT CHECK (resolution IN ('pending', 'refund_buyer', 'pay_seller', 'partial_refund')),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE disputes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "disputes_select_seller" ON disputes FOR SELECT USING (auth.uid() = seller_id);
CREATE POLICY "disputes_insert_any" ON disputes FOR INSERT WITH CHECK (true);
CREATE POLICY "disputes_update_any" ON disputes FOR UPDATE USING (true);

-- ============================================
-- AI VERIFICATIONS TABLE
-- AI check results for images
-- ============================================
CREATE TABLE IF NOT EXISTS ai_verifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  entity_type TEXT NOT NULL CHECK (entity_type IN ('item', 'krowba_link', 'shipping_proof')),
  entity_id UUID NOT NULL,
  verification_type TEXT NOT NULL CHECK (verification_type IN ('image_text_match', 'fake_detection', 'similarity_check', 'duplicate_check')),
  image_url TEXT NOT NULL,
  score DECIMAL(5, 4),
  confidence DECIMAL(5, 4),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'passed', 'warning', 'failed')),
  message TEXT,
  raw_response JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ai_verifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ai_verifications_select_all" ON ai_verifications FOR SELECT USING (true);
CREATE POLICY "ai_verifications_insert_any" ON ai_verifications FOR INSERT WITH CHECK (true);

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Generate short code for krowba links
CREATE OR REPLACE FUNCTION generate_short_code()
RETURNS TEXT AS $$
DECLARE
  chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result TEXT := '';
  i INTEGER;
BEGIN
  FOR i IN 1..8 LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Auto-create seller profile on signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO sellers (id, business_name, phone, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'business_name', 'My Business'),
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    NEW.email
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();

-- Update timestamp trigger
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sellers_updated_at BEFORE UPDATE ON sellers FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER items_updated_at BEFORE UPDATE ON items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER krowba_links_updated_at BEFORE UPDATE ON krowba_links FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER transactions_updated_at BEFORE UPDATE ON transactions FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER escrow_holds_updated_at BEFORE UPDATE ON escrow_holds FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER disputes_updated_at BEFORE UPDATE ON disputes FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================
CREATE INDEX IF NOT EXISTS idx_items_seller_id ON items(seller_id);
CREATE INDEX IF NOT EXISTS idx_krowba_links_seller_id ON krowba_links(seller_id);
CREATE INDEX IF NOT EXISTS idx_krowba_links_short_code ON krowba_links(short_code);
CREATE INDEX IF NOT EXISTS idx_transactions_krowba_link_id ON transactions(krowba_link_id);
CREATE INDEX IF NOT EXISTS idx_transactions_seller_id ON transactions(seller_id);
CREATE INDEX IF NOT EXISTS idx_escrow_holds_transaction_id ON escrow_holds(transaction_id);
CREATE INDEX IF NOT EXISTS idx_shipping_proofs_transaction_id ON shipping_proofs(transaction_id);
CREATE INDEX IF NOT EXISTS idx_disputes_transaction_id ON disputes(transaction_id);
